[package]
name = "iroh-gossip-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
iroh = "0.31.0"   
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.95"
rand = "0.8.5"
iroh-gossip = "0.31.0"
futures-lite = "2.6.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
data-encoding = "2.7.0"
clap = "4.5.28"
parse = "0.1.2"

